GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/1

###
POST http://localhost:3000/routes
Content-Type: application/json

{
  "name": "route test 1",
  "source_id": "ChIJkZUz0Gxnv5QREzx8vDyV_Y4",
  "destination_id": "ChIJjaMvlkhnv5QRNlyRxT99RHs"
}

### Maps

###Pegar o place_id 1
GET http://localhost:3000/places?text=av getulio vargas, bauru, 930

###Pegar o place_id 2
GET http://localhost:3000/places?text=confianca supermercado nacoes, bauru

###Directions between 2 places
GET http://localhost:3000/directions?originId=ChIJkZUz0Gxnv5QREzx8vDyV_Y4&destinationId=ChIJjaMvlkhnv5QRNlyRxT99RHs