FROM node:18-bullseye-slim AS base

ARG APP=backend-nest
ARG HOME=/home/node

#run image as a service
# ENV PNPM_HOME="/pnpm"
# ENV PATH="$PNPM_HOME:$PATH"

# RUN corepack enable
# COPY --chown=node:node . $HOME/$APP
# WORKDIR $HOME/$APP

# USER node
# RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --dev
# EXPOSE 3000

# CMD [ "pnpm", "start:dev" ]

#run image as a dev-container
WORKDIR $HOME/$APP
USER node
CMD [ "tail", "-f", "/dev/null" ]